---
- hosts: django-mango

  user: mango

  sudo: False

  vars_files:
    - vars.yml

  tasks:

    - name: pull changes from repo
      action: git repo=$repo_url dest=$repo_path branch=$repo_branch version=HEAD

    - name: setup dependencies
      action: shell . $venv_path/bin/activate && cd $repo_path && python setup.py develop

    - name: run migrations
      action: shell . $venv_path/bin/activate && cd $repo_path/mango && python manage.py migrate --noinput

    - name: collect static files
      action: shell . $venv_path/bin/activate && cd $repo_path/mango && python manage.py collectstatic --clear --noinput
      notify:
        - restart supervisord processes

    - name: make sure supervisor is running
      action: service name=supervisor state=started
      sudo: True

  handlers:
    - name: restart supervisord processes
      action: command supervisorctl restart all
      sudo: True
