---
- hosts: django-mango

  user: mango

  sudo: True

  vars_files:
    - vars.yml

  vars_prompt:
    supervisor_http_pasword: supervisor http server password (hashed with SHA)
    nginx_conf: which nginx configuration to use
    htpasswd_password: htpasswd password

  tasks:
    - name: install git
      action: apt pkg=git state=installed update-cache=yes

    - name: install nginx
      action: apt pkg=nginx state=latest

    - name: setup nginx config
      action: template src=templates/nginx_$nginx_conf.conf dest=/etc/nginx/conf.d/mango.conf
      notify:
        - restart nginx

    - name: make sure nginx is running
      action: service name=nginx state=started

    - name: install htpasswd
      action: apt pkg=python-pip state=latest

    - name: create htpassword file
      action: command htpasswd -dbc /home/mango/.htpasswd mango $htpasswd_password

    - name: install setuptools
      action: apt pkg=python-setuptools state=latest

    - name: install pip
      action: apt pkg=apache2-utils state=latest

    - name: install virtualenv
      action: command pip install virtualenv

    - name: create virtualenv
      action: command virtualenv $venv_path
      sudo: False

    - name: create logs directory
      action: shell mkdir -p $logs_path $public_path
      sudo: False

    - name: install supervisor
      action: apt pkg=supervisor state=latest

    - name: setup supervisor config
      action: template src=templates/supervisord.conf dest=/etc/supervisor/conf.d/mango.conf
      notify:
        - reload supervisord config

    - name: make sure supervisor is running
      action: service name=supervisor state=started

    # TODO for production:
    # - name: install database

  handlers:
    - name: restart nginx
      action: service name=nginx state=restarted

    - name: reload supervisord config
      action: command supervisorctl reload
