---
# NOTE: though we're not really at the point of requiring scaling so I think these could wait :D
- hosts: django-mango

  user: mango

  sudo: True

  vars_files:
    - vars.yml

  vars_prompt:
    supervisor_http_pasword: supervisor http server password (hashed with SHA)

  tasks:
  # TODO: install nginx
  # TODO: setup nginx config
  # TODO: install git
  # TODO: install virtualenv
  # TODO: create virtualenv if doesn't exist
  - name: create dirs
    action: shell mkdir -p $venv_path $logs_path
    sudo: False
  # TODO: install and run supervisor
  - name: setup supervisor config
    action: template src=templates/supervisord.conf dest=/etc/supervisor/conf.d/mango.conf
    notify:
    - reload supervisord config

  handlers:
  - name: reload supervisord config
    action: command supervisorctl reload
