---
# NOTE: though we're not really at the point of requiring scaling so I think these could wait :D
- hosts: django-mango

  user: mango

  vars_files:
    - vars.yml

  tasks:
  # TODO: install nginx
  # TODO: setup nginx config
  # TODO: install git
  # TODO: install virtualenv
  # TODO: create virtualenv if doesn't exist
  - name: create dirs
    action: shell mkdir -p $venv_path $conf_path $logs_path
  # TODO: install and run supervisor
  - name: setup supervisor config
    action: template src=templates/supervisord.conf dest=$conf_path/supervisord.conf
    notify:
    - reload supervisord config
    - restart supervisord processes

  handlers:
  # supervisord
  - name: reload supervisord config
    action: shell $venv_path/bin/supervisorctl -c $conf_path/supervisord.conf reload
  - name: restart supervisord processes
    action: shell $venv_path/bin/supervisorctl -c $conf_path/supervisord.conf restart all
